"""add_original_filename

Revision ID: 0bb5ad4caf47
Revises: a3d405d09591
Create Date: 2026-06-11 00:28:40.395619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bb5ad4caf47'
down_revision: Union[str, Sequence[str], None] = 'a3d405d09591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('original_filename', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'original_filename')
    # ### end Alembic commands ###
