/** usePreRecorded.ts
 * @authors: Anish Kumar, Bidipta Barua, Dibyasmita Hati, Arpan Haldar
 * @description: State management hook for pre-recorded video analysis.
 * @date: 10 June 2026
 * @returns: Pre-recorded analysis state and actions.
 *
 */


// Client Hook
"use client";


// Imports
import { useState } from "react";


// Pre Recorded Hook
export function usePreRecorded() {
  /* ---------------------------------------------------------------------- */
  /*                                State                                   */
  /* ---------------------------------------------------------------------- */

  const [videoFile, setVideoFile] =
    useState<File | null>(null);

  const [videoUrl, setVideoUrl] =
    useState("");

  const [transcript, setTranscript] =
    useState("");

  const [loading, setLoading] =
    useState(false);

  /* ---------------------------------------------------------------------- */
  /*                           Video Selection                              */
  /* ---------------------------------------------------------------------- */

  const handleVideoSelect = (
    file: File,
  ) => {
    setVideoFile(file);

    const url =
      URL.createObjectURL(file);

    setVideoUrl(url);

    setTranscript("");
  };

  /* ---------------------------------------------------------------------- */
  /*                           Process Video                                */
  /* ---------------------------------------------------------------------- */

  const processVideo = async () => {
    if (!videoFile) return;

    try {
      setLoading(true);

      // TODO:
      // Replace with actual API call.

      await new Promise(
        (resolve) =>
          setTimeout(resolve, 2000),
      );

      setTranscript(
        "This is a mock transcript generated by LipSpeak AI.",
      );
    } finally {
      setLoading(false);
    }
  };

  /* ---------------------------------------------------------------------- */
  /*                                Return                                  */
  /* ---------------------------------------------------------------------- */

  return {
    videoFile,

    videoUrl,

    transcript,

    loading,

    handleVideoSelect,

    processVideo,
  };
}