# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lipspeak/v1/inference.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'lipspeak/v1/inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1blipspeak/v1/inference.proto\x12\x0blipspeak.v1\"$\n\x13PredictVideoRequest\x12\r\n\x05video\x18\x01 \x01(\x0c\"*\n\x14PredictVideoResponse\x12\x12\n\ntranscript\x18\x01 \x01(\t\"\'\n\x16PredictRealtimeRequest\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\"-\n\x17PredictRealtimeResponse\x12\x12\n\ntranscript\x18\x01 \x01(\t2\xc9\x01\n\x10InferenceService\x12S\n\x0cPredictVideo\x12 .lipspeak.v1.PredictVideoRequest\x1a!.lipspeak.v1.PredictVideoResponse\x12`\n\x0fPredictRealtime\x12#.lipspeak.v1.PredictRealtimeRequest\x1a$.lipspeak.v1.PredictRealtimeResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lipspeak.v1.inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTVIDEOREQUEST']._serialized_start=44
  _globals['_PREDICTVIDEOREQUEST']._serialized_end=80
  _globals['_PREDICTVIDEORESPONSE']._serialized_start=82
  _globals['_PREDICTVIDEORESPONSE']._serialized_end=124
  _globals['_PREDICTREALTIMEREQUEST']._serialized_start=126
  _globals['_PREDICTREALTIMEREQUEST']._serialized_end=165
  _globals['_PREDICTREALTIMERESPONSE']._serialized_start=167
  _globals['_PREDICTREALTIMERESPONSE']._serialized_end=212
  _globals['_INFERENCESERVICE']._serialized_start=215
  _globals['_INFERENCESERVICE']._serialized_end=416
# @@protoc_insertion_point(module_scope)
