# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/grpc/protos/lipspeak/v1/inference.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+app/grpc/protos/lipspeak/v1/inference.proto\x12\x0blipspeak.v1\"$\n\x13PredictVideoRequest\x12\r\n\x05video\x18\x01 \x01(\x0c\"*\n\x14PredictVideoResponse\x12\x12\n\ntranscript\x18\x01 \x01(\t\"\'\n\x16PredictRealtimeRequest\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\"-\n\x17PredictRealtimeResponse\x12\x12\n\ntranscript\x18\x01 \x01(\t2\xc9\x01\n\x10InferenceService\x12S\n\x0cPredictVideo\x12 .lipspeak.v1.PredictVideoRequest\x1a!.lipspeak.v1.PredictVideoResponse\x12`\n\x0fPredictRealtime\x12#.lipspeak.v1.PredictRealtimeRequest\x1a$.lipspeak.v1.PredictRealtimeResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.grpc.protos.lipspeak.v1.inference_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PREDICTVIDEOREQUEST']._serialized_start=60
  _globals['_PREDICTVIDEOREQUEST']._serialized_end=96
  _globals['_PREDICTVIDEORESPONSE']._serialized_start=98
  _globals['_PREDICTVIDEORESPONSE']._serialized_end=140
  _globals['_PREDICTREALTIMEREQUEST']._serialized_start=142
  _globals['_PREDICTREALTIMEREQUEST']._serialized_end=181
  _globals['_PREDICTREALTIMERESPONSE']._serialized_start=183
  _globals['_PREDICTREALTIMERESPONSE']._serialized_end=228
  _globals['_INFERENCESERVICE']._serialized_start=231
  _globals['_INFERENCESERVICE']._serialized_end=432
# @@protoc_insertion_point(module_scope)
