# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.grpc.protos.lipspeak.v1 import inference_pb2 as app_dot_grpc_dot_protos_dot_lipspeak_dot_v1_dot_inference__pb2


class InferenceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictVideo = channel.unary_unary(
                '/lipspeak.v1.InferenceService/PredictVideo',
                request_serializer=app_dot_grpc_dot_protos_dot_lipspeak_dot_v1_dot_inference__pb2.PredictVideoRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_protos_dot_lipspeak_dot_v1_dot_inference__pb2.PredictVideoResponse.FromString,
                )
        self.PredictRealtime = channel.stream_stream(
                '/lipspeak.v1.InferenceService/PredictRealtime',
                request_serializer=app_dot_grpc_dot_protos_dot_lipspeak_dot_v1_dot_inference__pb2.PredictRealtimeRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_protos_dot_lipspeak_dot_v1_dot_inference__pb2.PredictRealtimeResponse.FromString,
                )


class InferenceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PredictVideo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictRealtime(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictVideo': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictVideo,
                    request_deserializer=app_dot_grpc_dot_protos_dot_lipspeak_dot_v1_dot_inference__pb2.PredictVideoRequest.FromString,
                    response_serializer=app_dot_grpc_dot_protos_dot_lipspeak_dot_v1_dot_inference__pb2.PredictVideoResponse.SerializeToString,
            ),
            'PredictRealtime': grpc.stream_stream_rpc_method_handler(
                    servicer.PredictRealtime,
                    request_deserializer=app_dot_grpc_dot_protos_dot_lipspeak_dot_v1_dot_inference__pb2.PredictRealtimeRequest.FromString,
                    response_serializer=app_dot_grpc_dot_protos_dot_lipspeak_dot_v1_dot_inference__pb2.PredictRealtimeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lipspeak.v1.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InferenceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PredictVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lipspeak.v1.InferenceService/PredictVideo',
            app_dot_grpc_dot_protos_dot_lipspeak_dot_v1_dot_inference__pb2.PredictVideoRequest.SerializeToString,
            app_dot_grpc_dot_protos_dot_lipspeak_dot_v1_dot_inference__pb2.PredictVideoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PredictRealtime(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/lipspeak.v1.InferenceService/PredictRealtime',
            app_dot_grpc_dot_protos_dot_lipspeak_dot_v1_dot_inference__pb2.PredictRealtimeRequest.SerializeToString,
            app_dot_grpc_dot_protos_dot_lipspeak_dot_v1_dot_inference__pb2.PredictRealtimeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
